<?php
	include('config/db_connection.php');
	$date=date('Y-m-d');
	$USER_NAME = $_POST["USER_NAME"];
	$USER_CONTACT = $_POST["USER_CONTACT"];
	$USER_ALTERNATIVE_CONTACT =$_POST["USER_ALTERNATIVE_CONTACT"];
	$USER_EMAIL = $_POST["USER_EMAIL"];
	$USER_PASSWORD = md5($_POST["USER_PASSWORD"]);
	 $sql = "INSERT INTO user_reg (USER_NAME,USER_CONTACT ,USER_ALTERNATIVE_CONTACT,USER_EMAIL  ,USER_PASSWORD,IS_ACTIVE,CREATED_ON) VALUES ('$USER_NAME','$USER_CONTACT' ,'$USER_ALTERNATIVE_CONTACT','$USER_EMAIL'  ,'$USER_PASSWORD',1,'$date')";
	$query = mysqli_query($con,$sql);
	echo $query;

?>
